scribe:
  auth:
    # login-url: https://scribe-hub-production.us.auth0.com
    login-url: https://scribe-hub-dev.us.auth0.com
    grant-type: client_credentials
    enable: true
    audience: api.dev.scribesecurity.com
    # audience: api.production.scribesecurity.com
    # url: https://airflow.scribesecurity.com
# url: https://airflow.dev.scribesecurity.com
    url: https://api.dev.scribesecurity.com
  
  enable: true
