name: git-sbom-and-image-sbom

env:
  
  APP_NAME: Mongo-Express
  VALINT_BOM_AUTHOR_NAME: Guy-Chernobrov
  VALINT_BOM_AUTHOR_EMAIL: gc@scribesecurity.com
  VALINT_BOM_AUTHOR_PHONE: 052-9281309
  VALINT_BOM_SUPPLIER_NAME: Scribe-Security
  VALINT_BOM_SUPPLIER_URL: www.scribesecurity.com
  VALINT_BOM_SUPPLIER_EMAIL: info@scribesecurity.com
  VALINT_BOM_SUPPLIER_PHONE: 001-001-0011
  INTEGRATION_TEST: 15s
  GITHUB_RUN_NUM: ${{ github.run_number }}
  
  LOGIN-URL: https://scribe-hub-dev.us.auth0.com
  # LOGIN-URL: https://scribe-hub-production.us.auth0.com
         
  SCRIBE_AUDIENCE: api.dev.scribesecurity.com
  # SCRIBE_AUDIENCE: api.production.scribesecurity.com
  
  SCRIBE_URL: https://api.dev.scribesecurity.com
  # SCRIBE_URL: https://airflow.scribesecurity.com
  
on:
  workflow_dispatch:
    #  pull_request:
    #  push:
    #    branches: [main]

concurrency:
  group: build-in-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout-attest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     

      - name: Generate signed SBOM for repo content clone
        uses: scribe-security/action-bom@master #ec2962f8ef167c7ae7541c14a514982e73ef4d80 # pin@master
        with:
          target: "git:."
          scribe-enable: true
          product-key: $APP_NAME
          product-version: v0.49.0
          scribe-login-url: $LOGIN-URL
          scribe-auth-audience: $SCRIBE_AUDIENCE
          scribe-url: $SCRIBE_URL
          scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          components: packages,files,dep
          format: attest
          force: true
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mongo-a:v0.49.0 

      - name: Generate signed image SBOM
        uses: scribe-security/action-bom@master #ec2962f8ef167c7ae7541c14a514982e73ef4d80 # pin@master
        with:
          target: "mongo-a:v0.49.0"
          scribe-enable: true
          product-key: $APP_NAME
          product-version: v0.49.0
          scribe-login-url: $LOGIN-URL
          scribe-auth-audience: $SCRIBE_AUDIENCE
          scribe-url: $SCRIBE_URL
          scribe-client-id: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_ID }}
          scribe-client-secret: ${{ secrets.SCRIBE_DEV_M2M_CLIENT_SECRET }}
          format: attest
          force: true
      
